### ISSUE TITLE
Installation Failed: Unable to load valid module manifest data from (Github url)

### ISSUE THREAD

**Issue by UmbraZeal** [misthero/dnd5e-custom-skills#12]
Cannot install this module from within foundry vtt in update 10.284

**Comment by caprichozow** [comment]
Yeah, version 9.280 here, same problem, for the 9.280 I think the correct link would be:
"https://raw.githubusercontent.com/misthero/dnd5e-custom-skills/v1.0.8/module.json"
But even using this one it instantly goes 100% but then get stuck on 100% forever, I also tried installing it with the zip version but then it doesn't show up, I think I might have another bug report, but I'll try and test it on 1.0.8 first when I'm able to get it

**Comment by caprichozow** [comment]
If you want a work around for it, go to the FoundryVTT page of the module, go over the version 1.1.0 which is the compatible one for v10 and click over "Manifest URL"
![image](https://user-images.githubusercontent.com/109267376/188361554-e7627efb-f3e8-45f2-806f-38101fba28b8.png)
Search for this in the page that it opens up
![image](https://user-images.githubusercontent.com/109267376/188361622-da25e34c-9348-42b6-a750-0dfa8c8ac2eb.png)
And click over "Raw"
![image](https://user-images.githubusercontent.com/109267376/188361710-4e0f3a96-ef4c-4623-a8a0-9797e4447673.png)
This screen should open up, get the download link, just download it, open up the rar, then the folder inside of it, and then you should go to your Foundry Modules folder, find the module folder, open it and then drag the following files from the zip to the folder:
![image](https://user-images.githubusercontent.com/109267376/188361901-9e23839f-71de-4b1b-b957-13dc12a93009.png)
The path to the module folder should be at AppData\Local\FoundryVTT\Data\modules\dnd5e-custom-skills

**Comment by misthero** [comment]
sorry guys, I've messed up the v1.0.8 manifest, should be fixed now
