### ISSUE TITLE
Request: Custom HP & HD widgets for custom damage systems

### ISSUE THREAD

**Issue by s520864** [misthero/dnd5e-custom-skills#15]
Some homebrew has special rulesets for separating HP from your character in various manners. Be it Madness, Armor Fragility, or other effects.

**Comment by misthero** [comment]
????

**Comment by BarmyBarney** [comment]
If I can offer a guess, the goal is to have the ability to add additional resources to the same section where is HP, hit dice, AC, etc. essentially, abbility to add, let's say "Mana" counter next to the HP counter. Or put "naked AC" instead of Initiative.
