### ISSUE TITLE
Create New Actor freezes with module 5e-Custom-Skills

### ISSUE THREAD

**Issue by Falerion-git** [misthero/dnd5e-custom-skills#16]
Hi,

I'm running Foundry VTT v10.284 with DnD5e 2.0.2 and 5e-Custom-Skills module v1.1.1 installed.
There are several other modules installed, but all are turned off.

I get these warnings and errors upon creating a new actor.

![image](https://user-images.githubusercontent.com/75955095/189214126-970288e8-49b0-4fed-8e0e-dbe754e134ff.png)

![image](https://user-images.githubusercontent.com/75955095/189214192-5fca993c-27de-4b8b-8604-5e9a0da46af3.png)

The creation process is extremely slow with the module turned on, compared to have no module installed.
Also, if I activate other modules, foundry vtt completely freezes, unfortunately without being able to get an error report. 
If I turn off 5e-Custom-Skill, but leave the other modules on, everything works fine.

Does someone might have an idea what went wrong in this case?

**Comment by misthero** [comment]
Thankyou.
You are totally right, DnD5e 2.0.2 enter a loop if there is a new skill (no problem with abilities).
Seems it is trying to "update" the skill objects from old dnd5e system to the new one, like a migration, for every actor again and again. I need to investigate more.

**Comment by misthero** [comment]
Ok, problem solved, it was a bug in DnD5e system. I talked with the system devs it will be fixed with next DnD5e version.

Thx @arbron 

https://github.com/foundryvtt/dnd5e/issues/1790

**Comment by caprichozow** [comment]
If you want to use them both, without having to turn Custom skills on and off to create a new character, get the 2.0.0-alpha v3 version of 5e, I tried using 2.0.1 and 2.0.2 but both are not working properly
The manifest link for it is "https://raw.githubusercontent.com/foundryvtt/dnd5e/v10-pack-migration/system.json"
You can just get their manifest and replace the "release-2.0.2/system.json" part with "v10-pack-migration/system.json" if you don't trust my links tho!
