### ISSUE TITLE
Errors pushing on character sheet creations

### ISSUE THREAD

**Issue by justinthejaguar** [misthero/dnd5e-custom-skills#17]
The system lags out with a mass number of errors. I have three skills added and one ability, which one of the skills relies on...
Skill/Dexterity
Skill/Con
Skill/Made up ability

![Screen Shot 2022-09-11 at 8 32 22 PM](https://user-images.githubusercontent.com/38022481/189556277-55adba80-a689-4c18-bcc8-98a0fd50bc88.png)

**Comment by misthero** [comment]
this is a problem with latest dnd5e system, read here: https://github.com/misthero/dnd5e-custom-skills/issues/16
