### ISSUE TITLE
Skills not hidden on NPC sheets

### ISSUE THREAD

**Issue by idiotekque** [misthero/dnd5e-custom-skills#21]
Hiding skills in the module settings works just fine for player characters, and hiding abilities works fine for any sheet, but I'm running into an issue where none of the skills set to hidden in the settings are actually hidden on NPC sheets.

![image](https://user-images.githubusercontent.com/107237012/218333599-3b903638-5d1a-4229-a763-7f5b76b98e11.png)

I'm on Foundry build 291 and DND5e 2.1.4. The screenshot is using TidySheet of course, but I'm getting identical behavior with the default sheet as well.

**Comment by misthero** [comment]
thank you for bringing this up, fixed in version 1.1.5, please update :)
