### ISSUE TITLE
Feature Request: Alphabetize List of Skills

### ISSUE THREAD

**Issue by cvilbrandt** [misthero/dnd5e-custom-skills#22]
![image](https://user-images.githubusercontent.com/60412756/219975937-f07378fb-9345-4460-93cb-5b56f5caba98.png)
Currently, the skill list has the unhidden core skills alphabetized, followed by the custom skills alphabetized. However, especially for some of my less adept players, having the list be split that way makes it hard for them to find what they're looking for.

I would like the option to have the full list of skills alphabetize without being split into two sections.

**Comment by misthero** [comment]
try latest version
