### ISSUE TITLE
(Issue) Tidy5e causing skill ability modifier to go to dex & not using new stats 

### ISSUE THREAD

**Issue by TookieKun** [misthero/dnd5e-custom-skills#24]
It's not leaving behind any errors that I can notice, I had to manually remove each module 1 by 1 to see what was causing the issue and it seems to only occur with Tidy5e (& maybe TidyUI - Game Settings?)

How to reproduce (from my experience at-least):
1: Make custom skills with different ability modifiers.
2: Create new actor

(Before)
![Report1](https://user-images.githubusercontent.com/107572957/222225946-88fe8718-e17e-4137-87b1-c35a62bf16e6.png)
(After)
![image](https://user-images.githubusercontent.com/107572957/222225910-47a68eee-72bb-47ed-a3b6-b1c8bc3945a0.png)

Note: A workaround for now if you want to keep Tidy is to disable it when creating the actor then re-enabling it after.

**Comment by p4535992** [comment]
@TookieKun  Can you specify module, system and foundry version ?

**Comment by misthero** [comment]
@TookieKun this should be fixed with latest tidy5e-sheet

@p4535992 thankyou for your help

**Comment by TookieKun** [comment]
Ty both for the quick work, sorry for not repsonding to the case sooner I was at work.
