### ISSUE TITLE
[BUG] CSS issue with tidy5e-sheet 

### ISSUE THREAD

**Issue by p4535992** [misthero/dnd5e-custom-skills#25]
I notice a little css incompatibility with tidy5e-sheet, on the hit config button on NPC

![](https://i.imgur.com/8EYQESi.png)

with a fast check, i can tell it should be enoug to remove this css line:

https://github.com/misthero/dnd5e-custom-skills/blob/d78e72db9ff1b717eb673e701ac92769ca23af31/css/dnd5e-custom-skills.css#L70

**Comment by misthero** [comment]
thx, didn't noticed that, the flex wrap is necessary when you add abilities in tidy5e sheet, I'll fix that.

**Comment by mmacgibbon** [comment]
I have a similar issue with the CSS, it affects the abilities portion:

![image](https://user-images.githubusercontent.com/2736379/224473299-83395a6a-dd5b-4de5-ba8d-fa61dc2020ae.png)

**Comment by misthero** [comment]
@mmacgibbon  sorry, that was a typo of mine, please update

**Comment by mmacgibbon** [comment]
> @mmacgibbon sorry, that was a typo of mine, please update

just did.  i like it the way you changed it.  it is changing the layout a bit, but i think its actually an improvement.

![image](https://user-images.githubusercontent.com/2736379/224506299-4b258e52-1a6e-48f7-bca3-71cd00cd728b.png)

**Comment by misthero** [comment]
I had to do that way with this module, since if you add custom abilities they will go on two lines overlapping with those buttons.

glad you like it.
