### ISSUE TITLE
Issues with custom abilities and skills that reference them.

### ISSUE THREAD

**Issue by MsVella** [misthero/dnd5e-custom-skills#27]
I'm having an issue where the names of custom abilities no longer show up after updating, this also applies to the ability in skills that reference them:
![Bug1](https://github.com/misthero/dnd5e-custom-skills/assets/88259742/5cececca-5c65-442f-b26e-9d598f1e9770)
![Bug2](https://github.com/misthero/dnd5e-custom-skills/assets/88259742/52dc2434-a9b0-4008-9e97-5831f6590f9e)

**Comment by misthero** [comment]
yep this is due to the data changes in dnd5e v.2.2

can you try this version?: https://github.com/misthero/dnd5e-custom-skills/tree/v1.2
