### ISSUE TITLE
Do not hide skills

### ISSUE THREAD

**Issue by WallaceMcGregor** [misthero/dnd5e-custom-skills#28]
It has recently stopped hiding selected skills. I don't know if it's because of the new versions of the module or D&D5. I attach a screenshot of the error that is shown multiple times in the console when opening the configuration window.

![CS Error](https://github.com/misthero/dnd5e-custom-skills/assets/17795541/810bbce0-841a-4b9b-abb5-c6541676f7bb)

**Comment by misthero** [comment]
that's due to dnd5e changing the data in v2.2 can you try this version: https://github.com/misthero/dnd5e-custom-skills/tree/dnd5e-v2.2-compatibility

**Comment by WallaceMcGregor** [comment]
I've tried that one and It works again! Thanks.

Is there plans to upgrade this fix?

**Comment by misthero** [comment]
live now :)
