### ISSUE TITLE
Skills not disappearing after removal

### ISSUE THREAD

**Issue by SLinxTheFox** [misthero/dnd5e-custom-skills#3]
I hit reset, didn't help, now the skill just has no name. i hid the skill, but then when i disabled the module it shows up again. How do i get rid of this?

**Comment by misthero** [comment]
hello @SLinxTheFox itn shoudn't do that.

could you please answer some questions to help me with debugging your issues? 

what version of dnd5e system are you using?

can you check if you have any error in browser console upon loading the world? (with the module enabled)

do you get an error in browser console when you press the reset button? 

did you changed the number of custom skills increasing it and than decreasing without deactivating some of it?

**Comment by misthero** [comment]
also try to reload the world (F5) after you reset, this should cause the actors to reload their data

**Comment by SLinxTheFox** [comment]
1: I'm on 1.5.6
2: I do have this:
```

> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'AbilityCua_0Abbr')
> [Detected 1 package: dnd5e-custom-skills]
>     at Function.applyToSystem (dnd5e-custom-skills.js:354)
>     at dnd5e-custom-skills.js:511
>     at Function._call (foundry.js:294)
>     at Function.callAll (foundry.js:253)
>     at Localization.initialize (foundry.js:4388)
>     at async Game.initialize (foundry.js:5425)

```
3: no errors when hitting reset, just unhides the skill
4: no change, all actors still have the skill
5: i didn't change any amounts before the issue occurred (that i can recall), but i did afterward in trying to get rid of it

**Comment by misthero** [comment]
ok found it, problem is with version 1.5.6 of dnd5e system, I had to install that version to replicate the issue.

if you update dnd5e system hit reset and reload the world everything should be fine.

**Comment by SLinxTheFox** [comment]
oh, it doesn't even show a notification for an update. I'll update it then, my bad, thank you!

**Comment by SLinxTheFox** [comment]
updated, no errors when hitting reset and only a few errors, related to other modules, on startup.

The skill is still there unfortunately. I did discover i get this error when i roll it

> `game.data.version is deprecated since V9 in favor of game.version


`
and this error when i try to change the proficiency

```

> entity.js:510 Error: Unresolved StringTerm Advantage requested for evaluation
>     at StringTerm.evaluate (foundry.js:9202)
>     at Roll._evaluateSync (foundry.js:6847)
>     at Roll.evaluate (foundry.js:6778)
>     at Actor5e._simplifyBonus (entity.js:507)
>     at Actor5e._prepareSkills (entity.js:487)
>     at Actor5e.prepareDerivedData (entity.js:160)
>     at Actor5e.prepareData (foundry.js:10772)
>     at Actor5e.prepareData (entity.js:62)
>     at Wrapper.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:511)
>     at Actor5e.prepareData (DAEdnd5e.js:722)
>     at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620)
>     at Actor5e.prepareDerivedResources (module.js:131)
>     at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620)
>     at Actor5e.🎁CONFIG.Actor.documentClass.prototype.prepareData#0 (libWrapper-wrapper.js:189)
>     at ClientDatabaseBackend._postUpdateDocumentCallbacks (foundry.js:10321)
>     at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:10250)
>     at ClientDatabaseBackend._updateDocuments (foundry.js:10131)
>     at async Function.updateDocuments (document.mjs:373)
>     at async Actor5e.update (document.mjs:456)
>     at async OGL5eCharacterSheet._onSubmit (foundry.js:3853)

```

**Comment by misthero** [comment]
this looks like a different issue, are you using ogl5e character sheet? and DAE module is there too.

I can't see any reference to this module in that error. 

anyway the reset button is still not working? did you updated your modules too?

also are you using the latest version (1.0.3) of my module??

**Comment by misthero** [comment]
Ok I'v found an incompatibility with OGL5e sheet (it wasn't a supported sheet anyway)

to remove every skill and ability try this: 

1. change every sheet to the default one, make sure OGL5e isn't used.
2. now hit reset button first, than click "Apply changes to world"
3. reload.

now your skills and abilities should have disappeared and you can use again OGL5e, this works in my tests

I will release a patch soon.

**Comment by misthero** [comment]
Check version v1.0.4

https://github.com/misthero/dnd5e-custom-skills/tree/v1.0.4

**Comment by SLinxTheFox** [comment]
oh! i've been pretty busy, sorry for the delay, but 1.0.4 seems to have worked! just a normal reset did it. thank you so much for adding that partial compatibility to the ogl sheet
