### ISSUE TITLE
Module Active but no configuration entries

### ISSUE THREAD

**Issue by SwordofSpirit** [misthero/dnd5e-custom-skills#30]
Foundry V10 Build 291
D&D 5e 2.1.5

I just installed the module, so it should be up to date. 

I activated this module, but can't find its functionality anywhere. There are no entries for it in Configure Settings.

I deactivated every other module, no change. I created a completely new world and activated just this module. Still nothing.

I'll be updating to V11 before I actually use it, but I thought it was worth reporting that it isn't showing up at all with the versions I currently have installed.

**Comment by misthero** [comment]
did you tried to update dnd5e system? the latest version of this module is updated for dnd5e v2.2+ maybe it lost compatibility with older version, if you want to use dnd5e v2.1 you should probably use the old v1.1.7 (https://github.com/misthero/dnd5e-custom-skills/releases/tag/v1.1.7)

didn't tested the new version with old dnd system, but this is my best guess at this moment

**Comment by SwordofSpirit** [comment]
Hmm. Could be. I haven't updated it yet because I believe I heard the newest version isn't backwards compatible with Foundry v10.

**Comment by misthero** [comment]
> Hmm. Could be. I haven't updated it yet because I believe I heard the newest version isn't backwards compatible with Foundry v10.

mmm... not sure, I'm on v.10 and dnd5e 2.2+ but maybe there is some bug I'm not aware of..

![immagine](https://github.com/misthero/dnd5e-custom-skills/assets/3662610/dde6d4fc-7a2c-4cd3-95db-7770d69b0514)

just be sure that the modules you are using are compatibles with dnd5e 2.2+

**Comment by SwordofSpirit** [comment]
Got it. Embarrassing user error (I had a similar sounding old module that I was activating instead).

Is there any chance of increasing the custom skill limit? I'm basically expanding each of the original skills into 3 skills (which goes over 50 right there), and I'd kind of like to have more for proficient/expertise checks for each ability score to cover tool proficiencies and some other things.

I'm also having that same problem I saw reported where the default skills won't hide.

**Comment by misthero** [comment]
about the skills not hiding, like I said if you are using dnd5e prior versions 2.2 than you should not update this module, they changed the character sheet so skills won't hide, problem is dnd5e custom skills v1.2 has already defined that the minimum system version to be dnd5e v2.2 but apparently this doesn't prevent the user from installing it on a previous version.


if you want to increase the skill number just replace the file 

\Data\modules\dnd5e-custom-skills\templates\skills-config.html

with this (extract the content and overwrite skills-config.html): 
[skills-config.zip](https://github.com/misthero/dnd5e-custom-skills/files/11718752/skills-config.zip)
