### ISSUE TITLE
Custom ability cannot be selected as default ability

### ISSUE THREAD

**Issue by Rorrenoa** [misthero/dnd5e-custom-skills#31]
![image](https://github.com/misthero/dnd5e-custom-skills/assets/12672232/f53cd573-cf90-4f86-af55-33cda2abf4e7)
![image](https://github.com/misthero/dnd5e-custom-skills/assets/12672232/3cdc0805-aeb4-4a3d-ac3b-771296ff7d25)
Foundry Version 11.301
dnd5e-custom-skills Version 1.2.0

Hi,
maybe the change of the availability in the abalities object is missing?

**Comment by misthero** [comment]
thx for reporting, I need to know something:
did you had the module configured with the custom skills before the update?

**Comment by Rorrenoa** [comment]
It's a freshly installed server. Without any configurations

**Comment by misthero** [comment]
You can now download the new version with this bug fixed

**Comment by Rorrenoa** [comment]
Perfect. Thank you very much
