### ISSUE TITLE
Conflict with DAE

### ISSUE THREAD

**Issue by Nedrapter** [misthero/dnd5e-custom-skills#32]
When having both DAE (https://gitlab.com/tposney/dae/-/issues/393) and this module activated, Actor effects that give bonuses to attributes or skills double their intended values. E.g. a +2 Dex effect , gives +4 instead.

**Comment by misthero** [comment]
you are lucky being able to configure DAE at all, on the latest version of Foundry: 11.305, latest version of dnd5e: 2.2.2 and latest version of DAE: 11.0.2 I'm not even able to configure a new effect with only dae, socketlib and libwrapper active.

Can you specify your setup so I can reproduce you issue?

**Comment by Nedrapter** [comment]
> you are lucky being able to configure DAE at all, on the latest version of Foundry: 11.305, latest version of dnd5e: 2.2.2 and latest version of DAE: 11.0.2 I'm not even able to configure a new effect with only dae, socketlib and libwrapper active.
> 
> custom-skills is NOT enabled in my test. So I would say that DAE is not working with the latest foundry + dnd5e system
> 
> Can you specify your setup so I can reproduce you issue?

Browser:
Opera, Firefox, Chrome

Foundry Version:
v10 303
Game System:
dnd5e 2.2.2

**Comment by misthero** [comment]
> Does that mean that this won't make to v11? I'm using few skills and 1 extra attribute and was thinking of updating to v11 in 2 weeks, as all other modules caught up recently.

can't speak of DAE but custom skills is already working in v11

so you are on Foundry v10, what DAE version and what dnd5e-custom-skills version gives you the problem?

**Comment by Nedrapter** [comment]
![image](https://github.com/misthero/dnd5e-custom-skills/assets/74311190/582165b0-e8fe-4956-8f77-feeb2fb62d51)
![image](https://github.com/misthero/dnd5e-custom-skills/assets/74311190/ecb669c6-67b6-4ff8-be55-53ea0e690e09)


> > Does that mean that this won't make to v11? I'm using few skills and 1 extra attribute and was thinking of updating to v11 in 2 weeks, as all other modules caught up recently.
> 
> can't speak of DAE but custom skills is already working in v11
> 
> so you are on Foundry v10, what DAE version and what dnd5e-custom-skills version gives you the problem?

I meant "won't make it as compatible with DAE" ... Mid-QoL relies on DAE and many things are expressed as active effects, including feats, spells, buffs.... :/

**Comment by misthero** [comment]
ok, I replicated the issue, it is caused by something I don't understand on DAE module, the problem is in file:
\Data\modules\dae\module\Systems\DAEdnd5e.js on line 273

removing the following code removes the double calculation, this code is only launched when custom-skills is active and it should be there to make dae compatible with 5e-custom-skills

 ``` 
if (game.modules.get("dnd5e-custom-skills")?.active) {
    wildcardEffects.push(/system\.skills\..*\.value/);
    wildcardEffects.push(/system\.skills\..*\.ability/);
    wildcardEffects.push(/system\.skills\..*\.bonuses/);
    wildcardEffects.push(/system\.abilities\..*\.value/);
}
```

you should give this information to DAE developer to help him find the issue here: https://gitlab.com/tposney/dae/-/issues/393

the 5e-custom-skills module doesn't do any calculation on the ability values. Just add or remove the skills and the abilities. than it is a regular skill or ability.

Anyway if [Tim Posney](https://gitlab.com/tposney) need me to change something on this module I will, no problem.

**Comment by Nedrapter** [comment]
I have relayed the information over there. Is this also the problem for v11? Or there is a different issue?

**Comment by misthero** [comment]
I think that v11 is something different, I cannot get DAE to work there even if it is the only module enabled.

**Comment by Nedrapter** [comment]
The last update on DAE for v11 seems to be working and I do not see any doubling effects anymore.
