### ISSUE TITLE
Modifier from effects get applied twice

### ISSUE THREAD

**Issue by Maravedis** [misthero/dnd5e-custom-skills#35]
Dnd Version: 2.3.1
Foundry Version: 10.303
Module version: 1.2.1

Hello. 
When using this module with DAE, if I use an effect to modify the value of an ability score, then the effect gets applied twice:
![image](https://github.com/misthero/dnd5e-custom-skills/assets/33416926/df8f6b6e-9637-47cc-bde2-721b050c7c6d)
![image](https://github.com/misthero/dnd5e-custom-skills/assets/33416926/4e345481-2b92-4223-9e5f-8d0bc1a9671c)
![image](https://github.com/misthero/dnd5e-custom-skills/assets/33416926/efa635cd-340e-44f9-bb6d-578c8893dafc)

As you can see, toggling the effect adding only one to wisdom, I get to 12 instead of 11.

If I turn off DAE, wisdom gets back to 11. Similarly, if I turn of 5e custom skills, it gets back to 11.

This is a fresh install of foundry, so I'm pretty sure it's some legacy configuration on my side. Do you have any idea of what's happening / is this fixable?

I tried looking at the code myself but was unable to isolate the source of the problem.

Thank you,
Maravedis

**Comment by misthero** [comment]
please read this: https://github.com/misthero/dnd5e-custom-skills/issues/32

**Comment by Maravedis** [comment]
Oooh, thank you very much, I'll fix it on my end.
