### ISSUE TITLE
NPC Character Sheets not Triggering CUB.

### ISSUE THREAD

**Issue by latorrex** [misthero/dnd5e-custom-skills#37]
I have set triggler to mark dead and unconcious for both NPCs and PCs. However, it does not work on NPCs that are using an NPC sheet.

From left to right, NPC Token with NPC Character Sheet, NPC Token with PC Character Sheet, PC Token with PC Character sheet. Triggers marked with NPC only only trigger on PC character sheets that don't have owners.

![Screenshot (16)](https://github.com/misthero/dnd5e-custom-skills/assets/146136446/5132258f-5e7a-467e-aac1-f0af9d6f54b7)

**Comment by misthero** [comment]
hello @latorrex , why do you think your issue is caused by this module?

**Comment by latorrex** [comment]
I think it has either to do with the Module or with the Current version of Foundry causing a change in how NPC sheets are read. I know it is not something that is in conflict with another mod because I disabled all other mods I had running in my world session. I had just recently updated my foundry and I'm currently running the latest version of CUB. Since the problem is that triggler is not triggering on any Token with an NPC sheet and PC sheets are treated as NPCs if they don't have ownership, I think that there was a change in how NPC sheets work with the newest foundry update.

**Comment by latorrex** [comment]
That's what the screenshot was for.
NPC Sheet, PC Sheet : No Ownership, PC Sheet : PC Ownership.

It's like NPC sheet tokens are treated as neither NPC or PC as determined by CUB

**Comment by misthero** [comment]
ok, but this module just add skills to actors, I don't understand what should I do to reproduce the issue. Can you explain your setup, what modules do you have enabled, what settings? Do you have custom skills or abilities activated?

Please give me the instructions to get to your results.
