### ISSUE TITLE
not all actors are being updated

### ISSUE THREAD

**Issue by mmacgibbon** [misthero/dnd5e-custom-skills#4]
I dont fully understand why, but when creating a new skill, only some of the actors are being updated.

**Comment by misthero** [comment]
hello, only owned actors will get the skills, did you read here? https://github.com/misthero/dnd5e-custom-skills/blob/main/README.md

is happening something different from that?

**Comment by mmacgibbon** [comment]
@misthero Yes, i figured it out.  basically what happens is that if you own any vehicles, it causes a JS error causing none of the other actors to fail.  

Its attempting to assign skills to an actor that cant have them.  (the vehicle)

**Comment by mmacgibbon** [comment]
ive tried with a custom or non custom.  it seems to hit it regardless.  this is when adding skills.  i think vehicles dont have the skills.    I will post the JS error later today.

**Comment by mmacgibbon** [comment]
```
foundry.js:3856 TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at dnd5e-custom-skills.js:464:74
    at Array.filter (<anonymous>)
    at CustomSkills.addSkillToActors (dnd5e-custom-skills.js:464:43)
    at CustomSkillsForm.<anonymous> (dnd5e-custom-skills.js:97:24)
    at Generator.next (<anonymous>)
    at fulfilled (dnd5e-custom-skills.js:6:54)
```

**Comment by mmacgibbon** [comment]
all i have to do is make sure the vehicle isnt owned by anyone and it works, but if the vehicle is owned by anyone i get this.

**Comment by misthero** [comment]
Latest version should fix the bug. 

Please update the module and let me know. Thank you.

https://github.com/misthero/dnd5e-custom-skills/commit/57f516ebb481f19c31f2b0ba101d72b11c202b58
