### ISSUE TITLE
No longer works with DnD 5e 3.0 update

### ISSUE THREAD

**Issue by morgannamaths** [misthero/dnd5e-custom-skills#41]
The big DnD 5e 3.0 update came out today and the custom skills didn't carry over. I tried removing and re-adding the module to no avail.

When I go to Configure Settings and click on Custom Abilities & Skills Configuration, the button does nothing - it doesn't open a new window or do anything. The box highlights orange and that's it.

![Screenshot from 2024-02-01 12-09-06](https://github.com/misthero/dnd5e-custom-skills/assets/122200270/d082b049-44ec-4dcb-9612-4a1747b6e0cb)

I believe this is more of an issue with the fact the 3.0 update bricked something rather than specifically an issue with the module, as it was working perfectly before.

**Comment by misthero** [comment]
I know, what I didn't know is that the dnd5e was going to change that radically. 
I'm sorry but the structure of the actors changed completely the module is not compatible right now with dnd3.0.0+.

This will need an update, I will probably make a different branch specifically for this version. I can't say how long will take.

**Comment by misthero** [comment]
looks like many modules won't work, on the officially reddit they suggest to stay on version 2+ for now until modules are updated.

![Screenshot_2024-02-01-09-27-17-51_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/misthero/dnd5e-custom-skills/assets/3662610/c060b7ca-e476-433d-9941-1c65b66e3493)

**Comment by Dalkan75** [comment]
I don't know if it's right to report it here, but it's also true that the form has been abandoned (if so, I apologize).
I solved it with TheRipper93's System Customizer.

**Comment by justinthejaguar** [comment]
> I know, what I didn't know is that the dnd5e was going to change that radically. I'm sorry but the structure of the actors changed completely the module is not compatible right now with dnd3.0.0+.
> 
> This will need an update, I will probably make a different branch specifically for this version. I can't say how long will take.

Will the new branch be a separate mod or just update when completed for future versions?

**Comment by misthero** [comment]
the latest update should fix this
