### ISSUE TITLE
I can't get any custom skills to show up, even after following the directions.

### ISSUE THREAD

**Issue by SwordofSpirit** [misthero/dnd5e-custom-skills#47]
Foundry 12.329
D&D 3.3.0
5e Custom Skills and Abilities 1.4.20

New world, no other modules.
I can hide existing skills, however if you unlock the sheet, they all reappear, and stay reappeared when you re-lock the sheet.
But I fiddled with it quite a bit and could not get new skills to show up at all.

**Comment by misthero** [comment]
thx for reporting. fixed
