### ISSUE TITLE
Languages Ita

### ISSUE THREAD

**Issue by Dalkan75** [misthero/dnd5e-custom-skills#5]
Greetings,
thank you very much for the module, it is really nice and it was just what I was looking for. Congratulations.
I am writing for a problem with languages: with the tidy sheet if I set my language, it's okay, if I also activate your module, it goes back to English.
How can I solve?
Thank you very much and sorry for my bad english.

Best Regards

Roberto

**Comment by misthero** [comment]
Hello Roberto,

what module or modules combination do you use for translating the sheet?
can you show me the list of installed modules you have?

Thank you.

**Comment by Dalkan75** [comment]
Hello :)
thanks for the quick reply.
The form is Tidy5e Sheet
![immagine](https://user-images.githubusercontent.com/108159546/178418927-91ff2837-a5d8-4453-8fa5-79d83b72fd44.png)
![immagine](https://user-images.githubusercontent.com/108159546/178418983-1014524c-1587-47f8-872e-d67b7cc5fcb8.png)

thanks again

**Comment by Dalkan75** [comment]
if it helps, in the Foundry that I use local (for testing) I have fewer modules, but the problem remains
![immagine](https://user-images.githubusercontent.com/108159546/178423716-686302d0-d9df-4570-9dae-53c4d5ee6100.png)

**Comment by misthero** [comment]
Ok Roberto, I think I've found the issue, please update the module and let me know.

**Comment by Dalkan75** [comment]
Perfect
it works

you are the best!
Thank you and best regards :)

**Comment by misthero** [comment]
Grazie per la conferma.
