### ISSUE TITLE
Proficiency value is not applied when updated by an Active Effect

### ISSUE THREAD

**Issue by TesseractLaboratories** [misthero/dnd5e-custom-skills#7]
The behavior of a custom skill does not match the behavior of a native skill when proficiency value is set by an active effect.
![image](https://user-images.githubusercontent.com/32314632/185778379-64a6dcf3-0f10-42d0-b431-a7bb4dc286a8.png)
![image](https://user-images.githubusercontent.com/32314632/185778385-343f8f6e-217f-408e-8c8a-ceb5756daf6f.png)

Looking at roll data, the ability values are structured differently, and the `multiplier` field is not being set.

![image](https://user-images.githubusercontent.com/32314632/185778424-310e1fd5-db9b-42c8-8fdf-808deca8bd79.png)

When manually selecting a proficiency value, the roll data is updated as expected.
![image](https://user-images.githubusercontent.com/32314632/185778562-41af07f6-f591-4084-b4aa-c44cae6e6e51.png)

**Comment by misthero** [comment]
Hello, I don't know, looks like it works for me, see attached video.

https://user-images.githubusercontent.com/3662610/185801483-3b75e497-d2e6-4250-80df-9a94e5897aaa.mp4

can you try opening the browser's  console and check if any error comes up?

also please specify foundry version, Custom Ability & Skills module version and active effect module version.

Thx

**Comment by misthero** [comment]
Sorry, I investigated, you arer right, but I don't know why..

This module is doing nothing special, just creating the skill in a similar fashion as the the dnd5e system does. 

When you click on the proficiency icon this module is doing nothing, is just the base dnd system doing his things.
If the base system is working and the proficiency is added correctly when you click on the icon than something is wrong with active effect in my opinion.

I will investigate more anyway

**Comment by TesseractLaboratories** [comment]
From what I can see, the data structure of how the custom skills are stored is different from how the dnd5e system stores skills.  The first console screenshot in my original post shows this comparison - see that `acr` has a "bonuses" entry, containing both `check` and `passive`, while `cus_1` does not (this has actually caused difficulties with other macros attempting to modify the passive bonus, since the custom skill doesn't have this field).

Wondering if the difference in structure is causing the issue when the dnd5e system tries to process the data?

**Comment by TesseractLaboratories** [comment]
Would it be unreasonable for a minor update to bring the overall structure to match the way the current dnd5e system is storing skill data? (shown in the screenshot for `acr`)

**Comment by TesseractLaboratories** [comment]
![image](https://user-images.githubusercontent.com/32314632/185808238-f3cf95a1-6366-41af-841c-4152059a12d4.png)
![image](https://user-images.githubusercontent.com/32314632/185808248-dcd7cd5d-cedf-4708-bf96-ae9d9b6d4d96.png)
![image](https://user-images.githubusercontent.com/32314632/185808256-52f74699-069e-4acf-bb01-94f776569534.png)
![image](https://user-images.githubusercontent.com/32314632/185808271-2b4b3024-e812-4483-95aa-c93f40240034.png)


my module/Foundry versions

**Comment by misthero** [comment]
> Would it be unreasonable for a minor update to bring the overall structure to match the way the current dnd5e system is storing skill data? (shown in the screenshot for `acr`)

that won't solve the problem, just try this file that introduces the bonuses object in the skill if you don't believe me:
[dnd5e-custom-skills.zip](https://github.com/misthero/dnd5e-custom-skills/files/9395946/dnd5e-custom-skills.zip)

my guess is that DAE is doing his own calculation based on default skills and not doing those calculations if it is a new skill that the module doesn't expect.

**Comment by TesseractLaboratories** [comment]
It's strange that it does successfully apply the proficiency check-mark, the sheet just doesn't calculate the actual proficiency.  I'll see if maybe I can set the other fields manually in the effect.

Is it still possible to include the bonuses object in a future update?
Even if it doesn't fix the proficiency issue, it would be nice to assign passive and active bonuses separately to custom skills, and I wonder if updating the default skill object being added would allow that.

**Comment by misthero** [comment]
I talked with DAE developer, he will try to roll out a fix, the problem is not in this module.

also, if you disable dae, active effects will work and proficiency correctly applied.

![immagine](https://user-images.githubusercontent.com/3662610/186845315-97956814-5d4f-4024-9c3d-59fb3a6c73a7.png)

**Comment by misthero** [comment]
Tim updated DAE anyway, now it should support this module too.

https://gitlab.com/tposney/dae/-/blob/master/Changelog.md
