### ISSUE TITLE
Not all skills are being added

### ISSUE THREAD

**Issue by Astrotech89** [misthero/dnd5e-custom-skills#8]
I'm working on adding skills to a module I'm building.  I'm currently on Testing channel of Foundry v10.279
Here's what I put in
<img width="522" alt="input" src="https://user-images.githubusercontent.com/20007225/187346038-488f772b-2627-4634-bbe9-6ff93c6ee8d2.png">
This is the result after hitting apply to a character sheet
<img width="163" alt="Result" src="https://user-images.githubusercontent.com/20007225/187346049-189889da-a332-49de-9c6b-cb0732d9adcb.png">
Then this is what I see at the settings page
<img width="522" alt="input" src="https://user-images.githubusercontent.com/20007225/187346051-cfe40986-09d3-411a-bb38-2e9cfd3fb18d.png">

It seems to delete my entries.

**Comment by misthero** [comment]
Also remember that if you keep your character sheet open, it won't always show the changes in real time you just made to skill configurations.

You should close and reopen the character sheet to see the real changes.

**Comment by BarmyBarney** [comment]
Another guy having same issue... tried that, not working.
Apparently, skills/abilities are added, but the label is added only for cua_0 or cus_0.

**Comment by BarmyBarney** [comment]
> Maybe you saved a first time without label, than unchecked activate, entered the label and rechecked activated again? or something like that.

Thought it might be the issue, since new spaces for new skills/abilities can only be added by changing the number of custom skills/abilities and saving... but no. Even with the default number, and putting things there right after disabling and re-enabling the module... it still does that. simply put, any skill or ability not on the first postition  will be added to character sheet, but not with the label.

**Comment by misthero** [comment]
that's not what I'm getting on a clean test world, do you get any errors in console? could it be some interaction with another module? 

![immagine](https://user-images.githubusercontent.com/3662610/188288688-0e452c7f-4b7b-44ec-ae9b-dcf72cf96248.png)

please check browser console for errors (like when you apply the settings or open the sheet)

also provide a list of installed modules.

**Comment by BarmyBarney** [comment]
> please check browser console for errors (like when you apply the settings or open the sheet)
if you tell me how and what to look for, sure.

> also provide a list of installed modules.
¨5e Custom abilities & skills
5e custom currency
5e feats
5e sheet resources plus
active auras
advanced macros
art gallery
better roll tables
combat ready!
combat uttility belt
compendium browser
compendium folders
compendium image m apper
crash's automatic blind rolls
crash's tracking & training
DFreds droptables
Dicetray
Easy Target
Forien's unidentified items
FXMaster
GM Notes
Health Estimate
Hidden Initiative
Hitpoint Tint
Chat Portrait
Illandrin's tidy module settings
Illandril's token tooltips
Initiative double click
Inventory+
Keybind Lib
Koboldworks - measurment info
Less fog
Let's trade 5e
lib- color settings
libWrapper
LootsheetNPC5e
math.js
midi QOL
Monk's active tile triggers
Monster blocks
Multilevel tokens
next up
permission viewer
playlist importer
point of interest sheet
polyglot
quick insert - search widget
settings extender
show art
simple calendar
skill customization for D&D5e
socketlib
split journal
the Furnace
token action HUD
token attacher
token auras
token info icons
token mold
turn alert
turn marker
variant encumbance
vehickles and mechanisms
wall height 
weather control

**Comment by misthero** [comment]
> if you tell me how and what to look for, sure.

sure, hit **F12** while foundry is open it should bring up some developer tools. Click on the console tab, than start changing settings, or opening your character sheet and check if any error appear.

![immagine](https://user-images.githubusercontent.com/3662610/188323487-1d8398d4-2652-4ad1-b02d-6cf811651005.png)

**Comment by BarmyBarney** [comment]
opening a character sheet produced these errors:

ReferenceError: SetupConfiguration is not defined
[Detected 3 packages: VariantEncumbrance, lib-wrapper, monks-active-tiles]
    convertItemSet VariantEncumbrance.js:189
    calculateEncumbrance VariantEncumbrance.js:358
    <anonymous> VariantEncumbrance.js:58
    _call foundry.js:294
    call foundry.js:279
    _render foundry.js:3119
    _render foundry.js:3766
    render foundry.js:3023
    render foundry.js:4261
    _onClickDocumentName foundry.js:47525
    call_wrapped libWrapper-wrapper.js:511
    clickDocumentName monks-active-tiles.js:4560
    call_wrapper libWrapper-wrapper.js:620
    _onClickDocumentName#0 libWrapper-wrapper.js:189
    jQuery 2
        dispatch
        handle

**Comment by BarmyBarney** [comment]
in the error tab specifically it produced this:
> Foundry VTT | Error thrown in hooked function '' for hook 'renderActorSheet'

**Comment by misthero** [comment]
thank you, can you try disabling VariantEncumbrance module?

**Comment by BarmyBarney** [comment]
disabled that... doesn't change anything... however, this time, when I saved the customs skills setup, it displayed this error (but opening character sheet didn't produce any error):

TypeError: game.i18n._fallback.DND5E is undefined
    applyToSystem dnd5e-custom-skills.js:406
    _updateObject dnd5e-custom-skills.js:123
    fulfilled dnd5e-custom-skills.js:6
    promise callback*step dnd5e-custom-skills.js:8
    __awaiter dnd5e-custom-skills.js:9
    __awaiter dnd5e-custom-skills.js:5
    _updateObject dnd5e-custom-skills.js:56
    _onSubmit foundry.js:3855
    _activateCoreListeners foundry.js:3793
    _render foundry.js:3091
    _render foundry.js:3766
    render foundry.js:3023
    onClickSubmenuWrapper colorSetting.js:20
    call_wrapper libWrapper-wrapper.js:595
    _onClickSubmenu#0 libWrapper-wrapper.js:189
    jQuery 9
    activateListeners foundry.js:55601
    activateListeners settings-extender.js:416
    _render foundry.js:3092
    _render foundry.js:3766
    render foundry.js:3023
    _onSettingsButton foundry.js:60167
    jQuery 2
        dispatch
        handle
[foundry.js:3858:15](http://178.17.2.76:30004/scripts/foundry.js)
    _onSubmit foundry.js:3858
    _activateCoreListeners foundry.js:3793
    _render foundry.js:3091
    _render foundry.js:3766
    render foundry.js:3023
    onClickSubmenuWrapper colorSetting.js:20
    call_wrapper libWrapper-wrapper.js:595
    _onClickSubmenu#0 libWrapper-wrapper.js:189
    jQuery 9
        dispatch
        handle
        (Async: EventListener.handleEvent)
    add
        Ee
        each
        each
        Ee
        on
        n
    activateListeners foundry.js:55601
    activateListeners settings-extender.js:416
    _render foundry.js:3092
    _render foundry.js:3766
    render foundry.js:3023
    _onSettingsButton foundry.js:60167
    jQuery 2
        dispatch
        handle

**Comment by BarmyBarney** [comment]
Now, I decided to turn off any and all of the charsheet add ons, and on re-enabling this one, and applying changes, skills were added, but not abilities.  console produced this error:

Foundry VTT | Rendering CustomSkillsForm [foundry.js:3055:15](http://178.17.2.76:30004/scripts/foundry.js)
TypeError: game.i18n._fallback.DND5E is undefined
    applyToSystem http://178.17.2.76:30004/modules/dnd5e-custom-skills/dnd5e-custom-skills.js:406
    _updateObject http://178.17.2.76:30004/modules/dnd5e-custom-skills/dnd5e-custom-skills.js:123
    fulfilled http://178.17.2.76:30004/modules/dnd5e-custom-skills/dnd5e-custom-skills.js:6
[foundry.js:3858:15](http://178.17.2.76:30004/scripts/foundry.js)
    _onSubmit http://178.17.2.76:30004/scripts/foundry.js:3858
Error: NetworkError when attempting to fetch resource.
URL adresa zdroje: moz-extension://b0c15ea6-33b2-4612-a317-239e329773f0/js/lib/purify.min.js
URL adresa zdrojové mapy: purify.min.js.map

**Comment by misthero** [comment]
> Now, I decided to turn off any and all of the charsheet add ons, and on re-enabling this one, and applying changes, skills were added, but not abilities. console produced this error:
> 
> Foundry VTT | Rendering CustomSkillsForm [foundry.js:3055:15](http://178.17.2.76:30004/scripts/foundry.js) TypeError: game.i18n._fallback.DND5E is undefined applyToSystem

sorry for the late answer, I think you are using some translation module, may I know what it is?

**Comment by BarmyBarney** [comment]
All the modules are listed above.  To my knowleedge there isn't any translation there. There is one to add custom "languages" such as elvish, dwarwish etc. could that be it?

**Comment by misthero** [comment]
sorry for being late, some real life problem called me back in september. How does it goes with the latest version?
